xpring-eng/sidechain-launch-kit

create_config_files.py, slk/chain.py, slk/sidechain.py, slk/testnet.py
This PR renames `Network` to `Sidechain` and refactors so that `Sidechain` inherits from `Chain`.
cleaning up the repo
CI passes. REPL works. Tests pass.
=> refactor: make `Network` inherit from `Chain`

slk/node.py, slk/testnet.py
Title says it all. It was really only using parts of `Node`.
refactoring repo
CI passes. RiplRepl runs as expected. Tests pass.
=> refactor: move bulk of `Sidechain.wait_for_validated_ledger` to Node

.github/workflows/lint.yml, create_config_files.py, poetry.lock, riplrepl.py, slk/chain.py, slk/chain_setup.py, slk/common.py, slk/config_file.py, slk/interactive.py, slk/log_analyzer.py, slk/node.py, slk/sidechain.py, slk/sidechain_params.py, slk/testnet.py
This PR adds typing in all source files of the repo, and adds a linter check for typing.
repo cleanup
CI passes. RiplRepl works as intended. Tests pass.
`mypy --strict`
=> refactor: adds typing everywhere

.env.example, poetry.lock, slk/chain_setup.py, slk/config/config_params.py, slk/create_config_files.py
This PR adds the ability to spin up a sidechain with any number of federators (between 1 and 8).
Desired feature for the launch kit
CI passes.
=> feat: make the number of federators variable

.flake8, slk/chain.py, slk/config/helper_classes.py, slk/config/network.py, slk/interactive.py, slk/log_analyzer.py, slk/testnet.py
This PR adds the linting back for all typing-related things.
repo cleanup
CI passes.
=> chore: add linting for typing

slk/chain/chain.py, slk/chain/chain_base.py
This PR creates a new base class for `Chain`, `ChainBase`, that contains all the core logic for `Chain`. This makes it easier to follow the logic and functions in `Chain`, because there are a lot of functions.
repo cleanup
CI passes. RiplRepl works as intended. Tests pass.
=> refactor: add helper class for Chain

poetry.lock, pyproject.toml
This PR allows people to use this project with Python 3.9.
CI passes. RiplRepl works as intended. Tests pass.
=> feat: add Python 3.9 support

CONTRIBUTING.md, README.md
=> docs: update the .md files to reflect the current state of the repo

poetry.lock, pyproject.toml
repo cleanup
CI passes. RiplRepl works as intended. Tests pass.
=> chore: remove unused dependencies

CONTRIBUTING.md, README.md, pyproject.toml, slk/create_config_files.py
This PR adds a CLI option for running the launch kit.
Setting up for beta release
=> feat: add CLI

poetry.lock, pyproject.toml, slk/chain/chain.py, slk/chain/mainchain.py, slk/chain/sidechain.py, slk/config/helper_classes.py, slk/repl/repl.py, slk/repl/repl_functionality.py, tests/simple_xchain_transfer_test.py, tests/utils.py
Title says it all. This PR also strips out all subscribe-related functionality, because it's not really needed anymore and would be a pain to keep in.
xrpl-py v1.3.0 contains all the features that the launch kit needs, which were previously on the `sidechain` branch of the repo (with some modifications, because that branch wasn't prod-ready). 
Tests pass. Everything works as designed.
=> refactor: use published version of xrpl-py instead of the separate branch

.env.example, slk/chain/chain_setup.py, tests/conftest.py, tests/simple_xchain_transfer_test.py, tests/utils.py
This PR resolves an issue where every time the sidechain was started up, the door seed would have to be reset.
As a consequence, this PR also generates a special door seed for tests.
See above
CI passes. Tests pass locally.
=> fix: resolve `tefMASTER_DISABLED` error

.env.example, CHANGELOG.md, README.md, pyproject.toml, slk/config/config_params.py
beta release
No code changes. CI passes. Tests pass locally.
=> release: bump version number for beta release

README.md, pyproject.toml
Needed to make the changes in order to publish.
Publish worked.
=> fix: fix TOML and installation instructions

slk/chain/chain.py, slk/repl/repl.py
This PR adds two patches.
1. A patch to import accounts into the address book from a secret seed.
2. A patch to add a new command to the interactive shell: `load_batch`. This takes a file as an argument and runs the commands in that file as if it were typed into the interactive shell.
=> Batch shell

slk/repl/repl.py
Will be used in conjunction with the ability to write batch scripts.
Tested in the REPL. Works as expected.
=> feat: Add `sleep` method to REPL

README.md
=> fix: fix door account seed description in README

slk/repl/__init__.py, slk/repl/repl.py, slk/run_shell.py, slk/sidechain_interaction.py, slk/sidechain_params.py
This PR removes all the bits of code that involve hooks, because we don't need that content in the main launch kit anymore.
general cleanup
CI passes.
=> chore: remove everything related to hooks

README.md, slk/config/config_params.py, slk/config/helper_classes.py, slk/config/network.py, slk/config/templates/sidechain.jinja, slk/create_config_files.py
This PR:
* Adds the ability to add any cross-chain assets, not just the USD one.
* Refactors to remove the need for `ExternalNetwork` (which felt very shoehorned into the pre-existing setup)
general cleanup/code simplification
Tests pass. CI passes.
=> refactor: simplify config creation

slk/run_shell.py, slk/sidechain_interaction.py, tests/simple_xchain_transfer_test.py
This PR simplifies `sidechain_interaction.py`. Previously, there were several parallel methods that all did the same thing. Those have now all been combined.
general repo cleanup
CI passes.
=> refactor: simplify `sidechain_interaction.py`

pyproject.toml
I haven't published a beta since December
N/A
=> release: publish updated beta

.github/workflows/test.yml, poetry.lock, pyproject.toml
Setup for better testing
CI passes. Code cov works as desired.
Improve the code coverage of the tests.
=> test: add pytest-cov for code coverage

README.md
Doc changes
Minor documentation changes.
NA
NA
NA
=> docs: minor documentation changes

README.md
=> docs: fix link to issues in readme
